// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Admin struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}

type AdminAuthPayload struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
	Admin        *Admin `json:"admin"`
}

type AuthPayload struct {
	Token        string    `json:"token"`
	RefreshToken string    `json:"refreshToken"`
	User         *AuthUser `json:"user"`
}

type AuthUser struct {
	ID           string  `json:"id"`
	Email        string  `json:"email"`
	Role         string  `json:"role"`
	FirstName    *string `json:"firstName,omitempty"`
	LastName     *string `json:"lastName,omitempty"`
	MobileNumber *string `json:"mobileNumber,omitempty"`
	Country      *string `json:"country,omitempty"`
	Address      *string `json:"address,omitempty"`
}

type Category struct {
	ID      string `json:"id"`
	StoreID string `json:"storeId"`
	Name    string `json:"name"`
	Slug    string `json:"slug"`
}

type CurrentUser struct {
	ID    string  `json:"id"`
	Email string  `json:"email"`
	Role  string  `json:"role"`
	Name  *string `json:"name,omitempty"`
}

type Customer struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
}

type CustomerAuthPayload struct {
	Token        string    `json:"token"`
	RefreshToken string    `json:"refreshToken"`
	Customer     *Customer `json:"customer"`
}

type CustomerWithStats struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	FullName string `json:"fullName"`
}

type LoginAdminInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginCustomerInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NewCategory struct {
	StoreID string `json:"storeId"`
	Name    string `json:"name"`
	Slug    string `json:"slug"`
}

type NewOrder struct {
	StoreID        string            `json:"storeId"`
	Items          []*OrderItemInput `json:"items"`
	IdempotencyKey *string           `json:"idempotencyKey,omitempty"`
}

type NewProduct struct {
	StoreID       string  `json:"storeId"`
	CategoryID    *string `json:"categoryId,omitempty"`
	Name          string  `json:"name"`
	Slug          string  `json:"slug"`
	Description   *string `json:"description,omitempty"`
	Price         float64 `json:"price"`
	StockQuantity int32   `json:"stockQuantity"`
	ImageURL      *string `json:"imageUrl,omitempty"`
	WeightGrams   *int32  `json:"weightGrams,omitempty"`
}

type NewStore struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description,omitempty"`
}

type Order struct {
	ID         string       `json:"id"`
	StoreID    string       `json:"storeId"`
	CustomerID string       `json:"customerId"`
	Status     string       `json:"status"`
	Total      float64      `json:"total"`
	Items      []*OrderItem `json:"items"`
}

type OrderItem struct {
	ID              string  `json:"id"`
	ProductID       string  `json:"productId"`
	Quantity        int32   `json:"quantity"`
	PriceAtPurchase float64 `json:"priceAtPurchase"`
}

type OrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int32  `json:"quantity"`
}

type OrderWithDetails struct {
	ID            string  `json:"id"`
	StoreID       string  `json:"storeId"`
	StoreName     string  `json:"storeName"`
	CustomerID    string  `json:"customerId"`
	CustomerEmail string  `json:"customerEmail"`
	Status        string  `json:"status"`
	Total         float64 `json:"total"`
}

type OwnerWithStats struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
	Country   *string `json:"country,omitempty"`
}

type PlatformStats struct {
	TotalStores    int32 `json:"totalStores"`
	TotalOwners    int32 `json:"totalOwners"`
	TotalCustomers int32 `json:"totalCustomers"`
	TotalOrders    int32 `json:"totalOrders"`
}

type Product struct {
	ID               string  `json:"id"`
	StoreID          string  `json:"storeId"`
	CategoryID       *string `json:"categoryId,omitempty"`
	Name             string  `json:"name"`
	Slug             string  `json:"slug"`
	Description      *string `json:"description,omitempty"`
	Price            float64 `json:"price"`
	StockQuantity    int32   `json:"stockQuantity"`
	ImageURL         *string `json:"imageUrl,omitempty"`
	WeightGrams      *int32  `json:"weightGrams,omitempty"`
	SuggestedPackage *string `json:"suggestedPackage,omitempty"`
}

type Query struct {
}

type RefreshPayload struct {
	Token string `json:"token"`
}

type RegisterCustomerInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	FullName string `json:"fullName"`
}

type RegisterInput struct {
	Email        string `json:"email"`
	Password     string `json:"password"`
	FirstName    string `json:"firstName"`
	LastName     string `json:"lastName"`
	MobileNumber string `json:"mobileNumber"`
	Country      string `json:"country"`
	Address      string `json:"address"`
}

type Store struct {
	ID          string  `json:"id"`
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description,omitempty"`
}

type StoreWithOwner struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	OwnerEmail   string `json:"ownerEmail"`
	OwnerName    string `json:"ownerName"`
	ProductCount int32  `json:"productCount"`
	OrderCount   int32  `json:"orderCount"`
}

type UpdateOrderStatusInput struct {
	Status string `json:"status"`
}

type UpdateProductInput struct {
	Name          *string  `json:"name,omitempty"`
	CategoryID    *string  `json:"categoryId,omitempty"`
	Slug          *string  `json:"slug,omitempty"`
	Description   *string  `json:"description,omitempty"`
	Price         *float64 `json:"price,omitempty"`
	StockQuantity *int32   `json:"stockQuantity,omitempty"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
	WeightGrams   *int32   `json:"weightGrams,omitempty"`
}

type UpdateStoreInput struct {
	Name        *string `json:"name,omitempty"`
	Slug        *string `json:"slug,omitempty"`
	Description *string `json:"description,omitempty"`
}
